[profile.default]
src = "src"
out = "out"
libs = ["lib/openzeppelin-contracts/contracts", "lib/forge-std/src"]
solc_version = "0.8.24"
auto_detect_remappings = true
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "forge-std/=lib/forge-std/src/"
]

[fmt]
line_length = 100
